- name: run playbook with shell command
  hosts: all 
  tasks:
    - shell: "pwd"
      args:
        chdir: "{{ playbook_dir }}"

    - shell: "ls"
      args:
        chdir: "{{ playbook_dir }}"

    - name: run playbook with shell command 
      shell: "ansible-playbook --version"
      args:
        chdir: "{{ playbook_dir }}"

    - name: run playbook with shell command 
      environment:
        ANSIBLE_NOCOLOR: 1
        ANSIBLE_HOST_KEY_CHECKING: 0
      command: "ansible-playbook --inventory=./inventory-build.ini ./test_external.yml"
      args:
        chdir: "{{ playbook_dir }}"
