- name: run playbook with shell command
  hosts: all 
  tasks:
    - shell: "pwd"
      args:
        chdir: "{{ playbook_dir }}"

    - shell: "ls"
      args:
        chdir: "{{ playbook_dir }}"

    - name: run playbook with shell command 
      shell: "ANSIBLE_NOCOLOR=1 ansible-playbook -i {{ playbook_dir }}/inventory-build {{ playbook_dir }}/test_external.yml"
      args:
        chdir: "{{ playbook_dir }}"
